### ISSUE TITLE
any plan to make a docker image include both java and maven?

### ISSUE THREAD

**Issue by godlockin** [bitnami/bitnami-docker-java#10]
and maybe build based on other OS images, e.g. centos .etc?

**Comment by beltran-rubo** [comment]
Thanks for your suggestion, this container image is specifically for OpenJDK. We will add your suggestion about Maven in our list of requests.

The Bitnami OS catalog is based on Debian 10, if you are interested on supporting other distributions or custom OS please check the VMware Tanzu Application Catalog https://tanzu.vmware.com/application-catalog
