### ISSUE TITLE
Jenkins fails after running container from command line

### ISSUE THREAD

**Issue by kishorkk91** [bitnami/bitnami-docker-java#13]
I was not able to run the java-example image and after running localhost:8080 then could not see Jenkins UI.
How to fix the issue?
`docker pull bitnami/java-example:0.0.1
`
`docker run -it --rm -p 8080:8080 bitnami/java-example:0.0.1
`
**localhost:8080**

![image](https://user-images.githubusercontent.com/59603187/151191772-7f703392-7e8f-4cc0-9c84-2317e87383fa.png)

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. We are working on deprecating this example because we are not maintaining or actively testing it anymore.

**Comment by kishorkk91** [comment]
Alright, no problem. Thanks for the quick update though.
