### ISSUE TITLE
Any chance of Java 9, 10, 11?

### ISSUE THREAD

**Issue by pete-woods** [bitnami/bitnami-docker-java#3]
This would make the image a lot more compelling for me. Also separate images for jre/jdk would be nice.

**Comment by marcosbc** [comment]
Hi @pete-woods, thanks for the suggestion! I've created an internal task for this, but I cannot provide an estimation for when we will start working on this.

In addition to that, something to keep in mind is that JDK 10.0.2 is the last available Oracle JDK free for production use, meaning we would need to move on to OpenJDK (requiring extra work refactoring our images).

Therefore, unfortunately I'm unable to give to give a hint when this would be implemented, but we will keep this issue updated with any news.

**Comment by pete-woods** [comment]
The Java 11 issue is definitely interesting. I guess I was assuming you'd just have to move to Oracle OpenJDK builds for that.

I also didn't expect this immediately, given I'm not paying for anything -- it was just the first thing that hit me when looking over this image.

**Comment by marcosbc** [comment]
That's fine! We actually do perform some processing on the current JRE/JDK bundle, as some of its binaries were not open source, meaning we might need to compare our bundle with OpenJDK, mainly for compatibility and functionality purposes.

Thanks again for the suggestion!

**Comment by pete-woods** [comment]
Looks like you already resolved this.
