### ISSUE TITLE
Vulnarabilities

### ISSUE THREAD

**Issue by prasad-1210** [bitnami/bitnami-docker-java#8]
Hello,

We were looking for images that are prebuilt, regularly maintained, smaller size, low vulnerability count. Thanks to your image as it checked most of the boxes except Vulnerabilities.

Pulled `bitnami/java:latest`
Run CVE scan on same using anchore with Debian and NVD CVE  DB.

`Detected: 7 High, 21 Medium, 10 Low, 147 Negligible, 7 Unknown Vulnerabilities`

Expected: Low vulnerabilities (At least all vulnerabilities with fixes should be mitigated) 

Is it something expected? what kind of prioritisation given to Vulnerability mitigation for new releases?

**Comment by beltran-rubo** [comment]
Hi @prasad-1210 

Thanks for reporting it. Unfortunately those issues are open by Debian itself and we can not fix them, you can see other scanners also report them https://quay.io/repository/bitnami/java?tab=tags. If you check "show only fixable" you will see those are empty. Our goal is to keep the containers up-to-date and with the latest system packages available and the latest versions. 

On the other hand, if you are thinking on using a different than Debian distribution for the RabbitMQ image (e.g. your own hardened base image or distribution), please check Tanzu Application Catalog https://tanzu.vmware.com/application-catalog
